### ISSUE TITLE
Error in bundled version of @structured-types/api-docs v3.46.12

### ISSUE THREAD

**Issue by throwaway39762** [ccontrols/structured-types#26]
So I've installed `@structured-types/api-readme`, tried to make use of it and got an error right away:

```
> @scope/component@0.2.0 docs /home/ubuntu/devel/my-react-component
> api-readme                                                                                            

processing file: /home/ubuntu/devel/my-react-component/README.md
(node:12035) UnhandledPromiseRejectionWarning: TypeError: URL is not a constructor                                                                             
    at src (/home/ubuntu/devel/my-react-component/node_modules/@structured-types/api-docs/dist/props-to-nodes2.js:3878:21)                    
    at getRepoPath (/home/ubuntu/devel/my-react-component/node_modules/@structured-types/api-docs/dist/props-to-nodes2.js:3954:21)            
    at processTicksAndRejections (internal/process/task_queues.js:95:5)                    
```

This is a tag in my README.md

```
<api-readme files="./src/index.tsx" collapsed="React.ReactNode"/>
```

Package versions:   
`@structured-types/api-docs` - `3.46.12`
`@structured-types/*` is also `3.46.12`
`@structured-types/typescript-config` - `3.46.9`

Node version is `14.19.3`

<details>
  <summary>Here's compiled code around <code>@structured-types/api-docs/dist/props-to-nodes2.js:3878:21</code></summary>

```javascript
const { URL } = url;

const URL_PATTERNS = new RegExp(/^\/?:?([/\w-.]+)\/([\w-.]+)\/?$/);
const GITHUB_API = new RegExp(/^\/repos\/([\w-.]+)\/([\w-.]+)\/(?:tarball|zipball)(?:\/.+)?$/);
const GITHUB_CODELOAD = new RegExp(/^\/([\w-.]+)\/([\w-.]+)\/(?:legacy\.(?:zip|tar\.gz))(?:\/.+)?$/);

var src = url => {
  const modifiedURL = url
    // Prepend `https` to the URL so that `url.URL` will see the value of `url` as an actual `url`, and therefore, correctly parse it.
    .replace(/^git@/, 'https://git@')

    // Replace `:` with `/` before path segments so that `url.URL` will see the value of `url` as an actual `url`, and therefore, correctly parse it.
    .replace(/git@([.\w]+):(?!\d)/, 'git@$1/')

    // Remove `.git` from any URL before applying regular expressions to the string. Removing `.git` through a non capture group is kind of difficult.
    .replace(/\.git$/, '');

  const parsedURL = new URL(modifiedURL, 'https://example.com/');
  const format = matches => {
    return { browse: createBrowseURL(parsedURL, matches), domain: parsedURL.host, project: matches[2] || null, type: getType(parsedURL), user: matches[1] || null };
  };
```
  
  and this is how `url` is defined above: 

```javascript

var url = {};

var util$1 = {
  isString: function(arg) {
    return typeof(arg) === 'string';
  },
  isObject: function(arg) {
    return typeof(arg) === 'object' && arg !== null;
  },
  isNull: function(arg) {
    return arg === null;
  },
  isNullOrUndefined: function(arg) {
    return arg == null;
  }
};

var punycode = require$$0__default$1["default"];
var util = util$1;

url.parse = urlParse;
url.resolve = urlResolve;
url.resolveObject = urlResolveObject;
url.format = urlFormat;

url.Url = Url;

function Url() {
  this.protocol = null;
  this.slashes = null;
  this.auth = null;
  this.host = null;
  this.port = null;
  this.hostname = null;
  this.hash = null;
  this.search = null;
  this.query = null;
  this.pathname = null;
  this.path = null;
  this.href = null;
}
```
</details>

This line that breaks everything comes from `@hutson/parse-repository-url` dependency (repo is already archived on github, deprecated?) but incorrect bundling is your build pipeline's doing.

to sum it up, it's trying to find URL in url object but that object has no such property. The shape of `url` object looks a lot like what [7 years old package from npm](https://www.npmjs.com/package/url) is exporting.

To me it looks like rollup either might be assuming it's compiling for the browser, so URL is expected to be available in the environment without importing anything (but then why it's reading from `url`?) or the native node package is not considered external and so the package from npm gets bundled with your module. 

I think for node there's no real reason to inline url package, it should be kept as external.  Especially it doesn't make sense to bundle other people's modules, these should live in node_modules, they're being installed by npm anyway. If you need it to run in the browser just have a separate entry point for it entirely entirely.

I guess it's just a mistake in rollup configuration. Sorry if I sounded passive aggressive in the paragraph above. Would be lovely to have it fixed

**Comment by throwaway39762** [comment]
oh, and this is where it's called from 

https://github.com/ccontrols/structured-types/blob/2188c1b88f8826684958602a60b3d73dfd78e929/packages/api-docs/src/package-info/package-info.ts#L61-L65
